package com.specure.core.domain.track

data class Track(
    val id: Long?, // null if new track
    val durationMillis: Long,
    val timestamp: String,
    val timestampRaw: Long,
    val downloadSpeed: Double?,
    val downloadSpeedUnit: String?,
    val downloadSpeedMegaBitsPerSec: String?,
    val downloadSpeedTestState: String?,
    val downloadSpeedTestError: String?,
    val downloadSpeedTestTimestamp: String?,
    val downloadSpeedTestTimestampRaw: Long?,
    val uploadSpeed: Double?,
    val uploadSpeedUnit: String?,
    val uploadSpeedMegaBitsPerSec: String?,
    val uploadSpeedTestState: String?,
    val uploadSpeedTestError: String?,
    val uploadSpeedTestTimestamp: String?,
    val uploadSpeedTestTimestampRaw: Long?,
    val latitude: Double?,
    val longitude: Double?,
    val locationTimestamp: String?,
    val locationTimestampRaw: Long?,
    val networkType: String?,
    val mobileNetworkOperator: String?,
    val mobileNetworkType: String?,
    val signalStrength: Int?,
    val networkInfoTimestamp: String?,
    val networkInfoTimestampRaw: Long?,
    val connectionStatus: String?,
    val temperatureCelsius: Double?,
    val temperatureTimestamp: String?,
    val temperatureTimestampRaw: Long?,
    val cellBand: String?,
    val cellBandFrequencyDownload: String?,
    val cellBandName: String?,
    val cellBandNameInformal: String?,
    var exported: Boolean = false,
)
